version: "3.7"
services:
  dovii:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - dovii-network
    ports:
      - "7070"
    labels:
      - "traefik.http.routers.dovii.rule=Host(`dovii.local`)"
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dovii-network
networks:
  dovii-network:
